#!/usr/bin/python3
from loguru import logger
from dotenv import load_dotenv

from core import IdealistaAPIManager, StorageManager, NoficationManager


load_dotenv()
logger.add('logfile', format="<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level><b>{level}</b></level> | {message}",
        colorize=True, diagnose=True)

logger.info(f'Starting idealistaParser.')
try:
    api = IdealistaAPIManager()
    storage = StorageManager()
    notification = NoficationManager()

    api.request_idealista()
    logger.info('Requested new houses from Idealista API.')

    storage.update_flats_in_database()
    logger.info(f'Inserted new houses into the database.')

    storage.send_out_new_flats(notification)
    logger.info(f'Sent out new flats to users.')
except Exception:
    logger.error(f'Something strange happened')

